# Generated by Django 3.1.7 on 2021-05-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recipe',
            new_name='post',
        ),
    ]
