# Generated by Django 3.1.7 on 2021-05-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
