# Generated by Django 3.1.7 on 2021-04-21 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=100)),
                ('acc_pwd', models.CharField(max_length=100)),
                ('acc_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=9999)),
                ('title_desc', models.TextField(default='Some random description')),
                ('title_us_score', models.FloatField(default=0)),
                ('title_au_score', models.FloatField()),
                ('title_date', models.DateField(verbose_name='date of film release')),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.accounts')),
            ],
        ),
    ]
