# Generated by Django 3.1.7 on 2021-04-21 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20210421_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=100)),
                ('acc_pwd', models.CharField(max_length=100)),
                ('acc_email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='review_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.extendeduser'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
