# Generated by Django 3.1.7 on 2021-04-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_title_title_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='title_au_score',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title_review',
        ),
    ]
