# Generated by Django 3.1.7 on 2021-05-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210423_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
